export const adjectives = [
    'sick',
    'trippy',
    'flirtatious',
    'kinky',
    'depressed',
    'spicy',
    'gay',
    'empty',
    'dead',
    'trashy',
    'recreational',
    'cold',
    'underwater',
    'clumsy',
    'greasy',
    'grumpy',
    'creepy',
    'high',
    'lonely',
    'messy',
    'loud',
    'juicy',
    'bougie',
    'itchy',
    'blushing',
    'slippery',
    'icy',
    'dizzy',
    'pregnant',
    'sneaky'
]

export default adjectives