const safe = [
    'hometown',
    'Jean-Luc Picard',
    'spaghetti western',
    'gutter punk',
    'Baxter',
    'wasps',
    'salad',
    'Pikachu',
    'Sailor Moon',
    'closet',
    'wizard',
    'troll',
    'pony',
    'fairy',
    'teapot',
    'banana',
    'therapist',
    'blacksmith',
    'jellyfish',
    'yogurt',
    'raven',
    'clown',
    'zebra',
    'teeth',
    'flowers',
    'Egypt',
    'weasel',
    'duck',
    'bat',
    'crawdad',
    'raccoon',
    'cricket',
    'spaceman',
    'doctor',
    'Rickrolling',
    'camel',
    'catnip',
    'ice cream',
    'megaphone',
    'tennis',
    'plumber',
    'DJ',
    'whale',
    'pop tab',
    'beach',
    'witch',
    'frog',
    'pants',
    'garbage',
    'pirate',
    'lawn mower',
    'robot',
    'birthday party',
    'violin',
    'lobotomy',
    'jail',
    'snail',
    'snake',
    'muffin',
    'genie',
    'lemon tree',
    'top hat',
    'Darth Vader',
    'knight',
    'disco',
    'beaver',
    'snowflake',
    'owl',
    'microwave',
    'swamp',
    'yak',
    'plant',
    'rocket ship',
    'ant hill',
    'cyclops',
    'monster',
    'boot',
    'camel',
    'watermelon',
    'can of beans',
    'motorcycle',
    'monster truck',
    'bacon',
    'butterfly',
    'school bus',
    'cubicle',
    'fridge',
    'punk',
    'emo',
    'goth'
]

const unsafe = [
    'drunk'
]

//currently defaulting to unsafe nouns!
function noun(safety) {
    if (safety) {
        return safe
    } else {
        return safe.concat(...unsafe)
    }
}

export default noun