const safe = [
    'hometown',
    'Jean-Luc Picard',
    'spaghetti western',
    'Baxter',
    'wasps',
    'salad',
    'Pikachu',
    'Sailor Moon',
    'closet',
    'wizard',
    'troll',
    'pony',
    'fairy',
    'teapot',
    'banana',
    'therapist',
    'blacksmith',
    'jellyfish',
    'yogurt',
    'raven',
    'clown',
    'zebra',
    'teeth',
    'flowers',
    'Egypt',
    'weasel',
    'duck',
    'bat',
    'crawdad',
    'raccoon',
    'cricket',
    'spaceman',
    'doctor',
    'Rickrolling',
    'camel',
    'catnip',
    'ice cream',
    'megaphone',
    'tennis',
    'plumber',
    'DJ',
    'whale',
    'pop tab',
    'beach',
    'witch',
    'frog',
    'pants',
    'garbage',
    'pirate',
    'lawn mower',
    'robot',
    'birthday party',
    'violin',
    'snail',
    'snake',
    'muffin',
    'genie',
    'lemon tree',
    'top hat',
    'Darth Vader',
    'knight',
    'disco',
    'beaver',
    'snowflake',
    'owl',
    'microwave',
    'swamp',
    'yak',
    'plant',
    'rocket ship',
    'ant hill',
    'cyclops',
    'monster',
    'boot',
    'camel',
    'watermelon',
    'can of beans',
    'motorcycle',
    'monster truck',
    'bacon',
    'butterfly',
    'school bus',
    'cubicle',
    'fridge',
    'punk',
    'emo',
    'goth'
]

const unsafe = [
    'drunk',
    'gutter punk',
    'lobotomy',
    'jail'
]

//currently defaulting to unsafe nouns!
function noun(safety) {
    return (safety ? safe : safe.concat(...unsafe))
}

export default noun